### ISSUE TITLE
How Do I use the Client?

### ISSUE THREAD

**Issue by zzx-the-neptune** [jidoc01/RustyDO#11]
No seriously, How Do I use the client on the rusty do server

Client:
Windows 10 (Host)/Windows XP (Guest)

Server:
Fedora 39 (Guest)

**Comment by jidoc01** [comment]
Unfortunately, we cannot provide how to play/use the client since GRAC (Game Rating and Administration Committee in Korea, 게임위) warned our project not to share any information about gaming stuff. We currently focus on server logic only in this project.
