### ISSUE TITLE
Instant disconnection

### ISSUE THREAD

**Issue by mariogamer2000** [jidoc01/RustyDO#13]
The server gets an 8 bytes long packet, and is then disconnected from the remote for unknown reasons.
The digimon.dll (renamed to digimon.exe!) client successfully connects to RustyDO server with TCP however. The client is called from X2Launcher.
![Screenshot_1](https://github.com/jidoc01/RustyDO/assets/171484640/275f4321-b0f0-4d9a-b621-576fb92a41f6)

**Comment by jidoc01** [comment]
Thank you for reporting the issue. It seems that our packet handler is not properly handling the 8-byte packet from the client side. Our current design assumes that a user selects a channel and types his account information to send a packet to the server, while the given screenshot seems to differ from our assumed case above. You may also enter the assumed case by providing parameters to the executable, which consists of two non-zero numbers sealed with quotes (e.g. "1 1").

I wonder if your situation is another login scenario for DO. To reproduce the case, could you elaborate on how you launched the game?

**Comment by mariogamer2000** [comment]
Hello. I wasn't aware of the parameters of the executable. I tried with "1 1" and it seems to connect and work perfectly fine. Perhaps this should be noted in the documents or readme. Thank you!
