### ISSUE TITLE
동글몬과 아이템 드롭 구현 질문

### ISSUE THREAD

**Issue by strike90** [jidoc01/RustyDO#16]
쿠루몬과 아이템 드롭에 관한 질문입니다.

현재는 쿠루몬. 템드랍이벤트가 전혀 발생하지 않습니다.

어느부분을 수정해줘야 하는가요??

**Comment by jidoc01** [comment]
안녕하세요.

> 현재는 쿠루몬. 템드랍이벤트가 전혀 발생하지 않습니다.

현재 동글몬과 아이템 드랍은 구현되어 있지 않습니다.

관련 이슈는 다음을 참고해주세요: https://github.com/jidoc01/RustyDO/discussions/9

> 어느부분을 수정해줘야 하는가요??

아이템과 동글몬은 각각 다음 루틴에서 처리합니다:
https://github.com/jidoc01/RustyDO/blob/231454f7a697829fa97dc9d9ae5ae86fc64f5813/server/src/server/login/handler/on_game.rs#L146

https://github.com/jidoc01/RustyDO/blob/231454f7a697829fa97dc9d9ae5ae86fc64f5813/server/src/server/login/handler/on_game.rs#L140

코딩 관련한 이야기는 다루지 않겠습니다 :D

상기 링크에서 이야기한 것처럼, 현재 아이템 및 동글몬 출현에 대한 논의가 전혀 되지 않은 터라, 구현을 보류중입니다.

다양한 의견들 기다리고 있습니다 :)

**Comment by jidoc01** [comment]
더불어 제목은 적절한 꼴로 변경하겠습니다~
